name: Test arm64

on:
  push

jobs:
  build:
    name: Test build binaries on arm64
    runs-on: ubuntu-latest-ARM64

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qq debhelper libcups2-dev
    - uses: actions/checkout@v2
    - name: Build
      run: fakeroot debian/rules binary
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ../*.deb
        file_glob: true
        tag: deb_packages_${{ github.ref }}
        overwrite: true
        body: "Release with generated deb packages"
